### ISSUE TITLE
Something is Wrong when use read()

### ISSUE THREAD

**Issue by HolyPeople** [2023-01-ESS-T10-Konkuk/SSH_Singuar_Smart_House#11]
Found a bug that blocks when using the virtual file function read

**Comment by pridom1118** [comment]
Thank you for your contribution :D
This works well now

**Comment by HolyPeople** [comment]
The problem was caused by the user writing the code like below :)

```c
if ((spi_fd = open("/dev/mcp3208dev0.0", O_RDWR) < 0) {}
```
So it was caused by a READ request to STDIN. 😄 

should modify that code to look like this.
```c
if ((spi_fd = open("/dev/mcp3208dev0.0", O_RDWR) < 0) {}
```

**Comment by pridom1118** [comment]
I'll never forget this in my life.
