### ISSUE TITLE
Role Assigned

### ISSUE THREAD

**Issue by HolyPeople** [2023-01-ESS-T10-Konkuk/SSH_Singuar_Smart_House#4]
# Role
- @pridom1118 
  - illuminance detection & Curtain Control 
- @kr1124 
  - temperature and humidity detection & FAN Control
- @HolyPeople 
  - GAS Detection & ALERT

**Comment by HolyPeople** [comment]
Test webhook

**Comment by HolyPeople** [comment]
Test

**Comment by pridom1118** [comment]
Got it 😀

**Comment by pridom1118** [comment]
Good job comrades.
