### ISSUE TITLE
Gas sensor: LED should be turned off at some point.

### ISSUE THREAD

**Issue by pridom1118** [2023-01-ESS-T10-Konkuk/SSH_Singuar_Smart_House#6]
# Need some features in the device driver for gas sensor   
LED should be turned off when the gas is no longer detected by the sensor.   
This feature can be implemented simply by adding another interrupt handler with rising edge trigger,   
or a function in the IOCTL.

**Comment by HolyPeople** [comment]
To effectively utilize the SPI read virtual file function that has been developed, I propose implementing a gas concentration monitoring system at the user level. The system will be designed to measure gas concentration and trigger specific actions when it falls below a predetermined threshold. In this case, the desired action involves controlling an LED using the IOCTL interface.
