### ISSUE TITLE
MCP3208: Adding a new converter for light sensor?

### ISSUE THREAD

**Issue by pridom1118** [2023-01-ESS-T10-Konkuk/SSH_Singuar_Smart_House#7]
# MCP3208: Light sensor also needs MCP3208   
Currently the gas sensor is using MCP3208 to detect flammable gases,   
and the light sensor also needs MCP3208 for light detection.   
So should we use another MCP3208 just for the light sensor,   
or just use another channel for the current one? (separation might be required)   
   
I think this issue is also related to the design for our IoT System -   
whether we should use single or multiple Raspberry Pis for this project.   

Would love to hear any suggestions or ideas for this problem 😀

**Comment by HolyPeople** [comment]
I will separate the SPI communication from the GAS module.
Please assign me.
